"""empty message

Revision ID: 37e0fab845ff
Revises: cccc61ddf3f1
Create Date: 2024-09-16 10:37:37.178943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e0fab845ff'
down_revision = 'cccc61ddf3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_credential',
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('end_date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('key_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_credential')
    # ### end Alembic commands ###
