"""Update PK in PasswordCredentials table

Revision ID: 3e9de17c8e4e
Revises: 4d6fe6a47530
Create Date: 2024-09-15 18:41:21.752537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9de17c8e4e'
down_revision = '4d6fe6a47530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_credential', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
