"""empty message

Revision ID: 4d47ce5b3dc8
Revises: eba3e1a0a19f
Create Date: 2024-09-17 18:50:32.573324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d47ce5b3dc8'
down_revision = 'eba3e1a0a19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enterprise_application_id', sa.String(length=128), nullable=False))
        batch_op.create_foreign_key(None, 'enterprise_application', ['enterprise_application_id'], ['app_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saml_certificate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enterprise_application_id')

    # ### end Alembic commands ###
