"""empty message

Revision ID: 7d4ab25ec2ed
Revises: c437d4dd5bb0
Create Date: 2024-09-17 18:18:52.269473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d4ab25ec2ed'
down_revision = 'c437d4dd5bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_display_name', sa.String(length=256), nullable=False))
        batch_op.drop_column('saml_display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saml_display_name', mysql.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('certificate_display_name')

    # ### end Alembic commands ###
