"""Update DB schema for app registration

Revision ID: 9b28a1e7f821
Revises: 0a31e359ffea
Create Date: 2024-09-15 15:54:14.892305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b28a1e7f821'
down_revision = '0a31e359ffea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('app_id', sa.String(length=128), nullable=False),
    sa.Column('odata_type', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('password_credential',
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('end_date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.app_id'], ),
    sa.PrimaryKeyConstraint('key_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_credential')
    op.drop_table('application')
    # ### end Alembic commands ###
