"""Update DB schema for Enterprise Application

Revision ID: c437d4dd5bb0
Revises: 37e0fab845ff
Create Date: 2024-09-17 18:16:35.923555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c437d4dd5bb0'
down_revision = '37e0fab845ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_application',
    sa.Column('app_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('saml_display_name', sa.String(length=256), nullable=False),
    sa.Column('end_date_time', sa.DateTime(), nullable=False),
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enterprise_application')
    # ### end Alembic commands ###
